sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pzMwyllEdDtoLSB0dtugX3KqgdidSlmua5TZslC74Bmu+YHxQoayi7i/2UgEnrdAPjOdaKtGC5HRV9LgM+XLL2iubRe/Bx9zvXzku/G/2RWSR/ehX+pI38hq2dCB08eahT5SqXi1lVfrSI1C0rTpxB6pygABGFYlLxUSgv7Yz3b/5rgk4DiUyc5Wf68f0Xry5G69RZ+qF5VkpfmzVNdf8UxRb8aYcq1rGdj/ri1bPs8Vcr+YeoeyWOtqvaxJ8SEZ+wpy3G/Rhvz/1QvB8+W6zj7jBbi2g1Gevu518Y6cVYr9TgcH9NBPuROu60Ki4Bxhd1lBRtBb9qCtJfJXksumJ2UVQl8JF8F/QS12U1FU75/uSlRtHaI4D12l0q8ey+FU62xHcnxsP5vCfVYz6ozXTAHvUIHc+whtojkRKaNdLce4VgqYKDsKZAdPKdIhx0Ih8xIRvmpgcmVgPQb4ty3ALKuk54fThtwbam7tRAg8GpmQHE3HWEWQ7oSuS/KoDTv3r/7t9N2G3cbiT69qpakKWRQiFYGFlqTaSWFFIb/plBu7mBTO/jW1bdHgPZNeNtrBtG0uY9tEqzduJs30QUhJugbaxxU/vUwCpUgeSVfnMCc7OPN5TXGkNcNvC5YNkoVgFjZ5G9ejH0lnQ/xG1C0e/4qqKbLRdkVYu19xY+HaB1s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Nonsense-Novels_4682
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy